# Render.com BuildWise API Configuration
# This file contains the configuration for deploying BuildWise API on Render.com

# Build Command (if needed)
# pip install -r requirements.txt

# Start Command
# gunicorn app.main:app --config gunicorn.conf.py

# Environment Variables needed:
# PORT - automatically set by Render.com
# DATABASE_URL - your database connection string
# SECRET_KEY - your application secret key
# ALLOWED_ORIGINS - comma-separated list of allowed origins for CORS

# Optional Environment Variables:
# WORKERS - number of worker processes (default: 2)
# LOG_LEVEL - logging level (default: info)