from fastapi import APIRouter

from . import auth, users, projects, tasks, documents, milestones, quotes, messages, gdpr, cost_positions, buildwise_fees, geo, finance_analytics, subscriptions, expenses, credits, inspections, appointments, milestone_progress, ratings, acceptance, invoices, visualizations, notifications, resources, contacts, notification_preferences, financial_charts, user_rank

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(projects.router)
api_router.include_router(tasks.router)
api_router.include_router(documents.router)
api_router.include_router(milestones.router)
api_router.include_router(quotes.router)
api_router.include_router(messages.router)
api_router.include_router(gdpr.router)
api_router.include_router(cost_positions.router)
api_router.include_router(buildwise_fees.router)
api_router.include_router(geo.router)
api_router.include_router(finance_analytics.router)
api_router.include_router(subscriptions.router)
api_router.include_router(expenses.router)
api_router.include_router(credits.router)
api_router.include_router(inspections.router)
api_router.include_router(appointments.router)
api_router.include_router(milestone_progress.router)
api_router.include_router(ratings.router)
api_router.include_router(acceptance.router)
api_router.include_router(invoices.router)
api_router.include_router(visualizations.router)
api_router.include_router(notifications.router)
api_router.include_router(resources.router)
api_router.include_router(contacts.router)
api_router.include_router(notification_preferences.router)
api_router.include_router(financial_charts.router)
api_router.include_router(user_rank.router)
