"""Create buildwise fees tables

Revision ID: create_buildwise_fees_tables
Revises: 
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'create_buildwise_fees_tables'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Erstelle buildwise_fees Tabelle
    op.create_table('buildwise_fees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('quote_id', sa.Integer(), nullable=False),
        sa.Column('cost_position_id', sa.Integer(), nullable=False),
        sa.Column('service_provider_id', sa.Integer(), nullable=False),
        sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('quote_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('invoice_number', sa.String(length=50), nullable=True),
        sa.Column('invoice_date', sa.Date(), nullable=True),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('payment_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('invoice_pdf_path', sa.String(length=255), nullable=True),
        sa.Column('invoice_pdf_generated', sa.Boolean(), nullable=True),
        sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('fee_details', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.Column('updated_at', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Erstelle buildwise_fee_items Tabelle
    op.create_table('buildwise_fee_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('buildwise_fee_id', sa.Integer(), nullable=False),
        sa.Column('quote_id', sa.Integer(), nullable=False),
        sa.Column('cost_position_id', sa.Integer(), nullable=False),
        sa.Column('quote_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Erstelle Indizes
    op.create_index(op.f('ix_buildwise_fees_id'), 'buildwise_fees', ['id'], unique=False)
    op.create_index(op.f('ix_buildwise_fees_invoice_number'), 'buildwise_fees', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_buildwise_fee_items_id'), 'buildwise_fee_items', ['id'], unique=False)
    
    # SQLite unterstützt keine ALTER-Constraints, daher werden Foreign Keys und Check Constraints
    # auf Anwendungsebene validiert
    # Foreign Key Constraints werden in den SQLAlchemy-Modellen definiert
    # Check Constraints werden in den Pydantic-Schemas validiert
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Entferne Indizes
    op.drop_index(op.f('ix_buildwise_fee_items_id'), table_name='buildwise_fee_items')
    op.drop_index(op.f('ix_buildwise_fees_invoice_number'), table_name='buildwise_fees')
    op.drop_index(op.f('ix_buildwise_fees_id'), table_name='buildwise_fees')
    
    # Entferne Tabellen
    op.drop_table('buildwise_fee_items')
    op.drop_table('buildwise_fees')
    
    # ### end Alembic commands ### 