"""Fix buildwise fees datetime columns

Revision ID: fix_buildwise_fees_datetime_columns
Revises: create_buildwise_fees_tables
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fix_buildwise_fees_datetime_columns'
down_revision = 'create_buildwise_fees_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # SQLite unterstützt kein ALTER COLUMN, daher müssen wir die Tabellen neu erstellen
    # Für SQLite verwenden wir eine andere Strategie
    
    # Aktualisiere bestehende Daten mit aktuellen Timestamps
    # PostgreSQL-kompatible Version
    op.execute("""
        UPDATE buildwise_fees 
        SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP 
        WHERE created_at IS NULL OR updated_at IS NULL
    """)
    
    op.execute("""
        UPDATE buildwise_fee_items 
        SET created_at = CURRENT_TIMESTAMP 
        WHERE created_at IS NULL
    """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 